OrsaAkademi.demo.WebApp/Controllers/PersonelEklemeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OrsaAkademi.demo.models;
using OrsaAkademi.demo.models.Entity;
using OrsaAkademi.demo.models.Entity.vmmodel;
using OrsaAkademi.demo.WebApp.Models.Interface;
using System.Collections.Generic;
using System.Threading.Tasks;
namespace OrsaAkademi.demo.WebApp.Controllers
{
    public class PersonelEklemeController : Controller
    {
        private readonly IPersonellerService _PersonellerService;

        public PersonelEklemeController(IPersonellerService personellerService)
        {
            _PersonellerService = personellerService;
        }

        
        public IActionResult PersonelListesi()
        {
            //string userEmail = HttpContext.Session.GetString("UserEmail");
            //if (string.IsNullOrEmpty(userEmail))
            //{

            //    return RedirectToAction("KayitEkrani", "PersonelGirisVeKayit");
            //}

            return View();
        }
        [HttpGet]
        public async Task<List<vmPersonelListele>> PersonelListeleme()
        {
            var result = await _PersonellerService.PersonelleriListeleService();
                return result;
        }
        public IActionResult PersonelEkleme()
        {
            string userEmail = HttpContext.Session.GetString("UserEmail");
            if (string.IsNullOrEmpty(userEmail))
            {

                return RedirectToAction("KayitEkrani", "PersonelGirisVeKayit");
            }
            return View();

        }
        


        [HttpPost]
        public async Task<Personeller> PersonelEkleme2(Personeller personeller)
        {
            var result =await _PersonellerService.PersonellerKaydetService(personeller);
            return result;
        }



        [HttpPost]
        public async Task<List<MedyaKutuphanesi>> PersonelFotografiKaydet(IFormCollection fotografyuklemealani)
        {
            if (fotografyuklemealani.Files.Count > 0)
            {
                var result = await _PersonellerService.PersonelFotografiKaydetService(fotografyuklemealani);
                return result;
            }
            else
            {
                return null;
            }
        }


        [HttpDelete]
        public async Task<bool> PersonelSil(int id)
        {
            var result = await _PersonellerService.PersonelSil(id);

            return result;
        }





    }
}

OrsaAkademi.demo.WebApp/Views/PersonelEkleme/PersonelEkleme.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Yeni Personel Ekle</h2>
<div class="container">
    <div class="row">
        <div class="col-md-7 col-sm-12 mr-2 mt-2 py-5 shadow-lg p-3 mb-5 bg-white rounded">
           
            <form id="PersonelForm">
                <div class="form-group row mb-5">
                    <div class="col-md-4">
                        <label for="PersonelAd" class="col-md-12 col-form-label mb-1"> <p class="text-sm-end mb-1">Personel Adı:</p> </label>
                        <div class="container-fluid">
                            <input type="text" class="form-control" name="ad" id="PersonelAd" />
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="PersonelSoyAd" class="col-md-12 col-form-label mb-1"> <p class="text-sm-end mb-1">Personel Soyadı:</p> </label>
                        <div class="container-fluid">
                            <input type="text" class="form-control" id="PersonelSoyad" />
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="PersonelTelefon" class="col-12 col-form-label mb-1"> <p class="text-sm-end mb-1">Personel Telefon:</p> </label>
                        <div class="container-fluid">

                            <input type="text" class="form-control" id="PersonelTelefon" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="PersonelDogumTarihi" class="col-12 col-form-label mb-1"><p class="text-sm-end mb-1">Personel Doğum Tarihi:</p></label>
                        <div class=" col-12 container-fluid">
                            <input type="date" class="form-control" id="PersonelDogumTarihi" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="PersonelEmail" class="col-12 col-form-label mb-1 "> <p class="text-sm-end mb-1">Personel Email:</p> </label>
                        <div class="col-12 container-fluid">
                            <input type="email" class="form-control" id="PersonelEmail" />
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="Sifre" class="col-12 col-form-label mb-1 "> <p class="text-sm-end mb-1">Şifre:</p> </label>
                        <div class="col-12 container-fluid">
                            <input type="password" class="form-control" id="Sifre" />
                        </div>
                    </div>
                    <div class="col-md-6 mb-5">
                        <label for="TekrarSifre" class="col-12 col-form-label mb-1"> <p class="text-sm-end mb-1">Şifreyi Tekrar Giriniz:</p> </label>
                        <div class="col-12 container-fluid">
                            <input type="password" class="form-control" id="TekrarSifre" />
                        </div>
                    </div>

                </div>
              
            </form>
            <div id="okulAlan_1" class="form-group row mb-5 justify-content-center form-school">
                <div class="col-sm-8 col-md-10 border rounded">
                    <div class="row mb-4 mt-2">
                        <div class="col-sm-12 col-md-8">
                            <div class="row">
                                <div class="col-6">
                                    <div class="row">
                                        <label for="okul" class="col-sm-12 col-form-label"><p class="text-sm-center">Mezun Okulunuz</p></label>
                                        <div class="col-sm-12 container-fluid">
                                            <select class="form-control" id="okul_1"></select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="row">
                                        <label for="mezuniyet" class="col-sm-12 col-form-label"><p class="text-sm-center">Mezuniyet Yılı</p></label>
                                        <div class="col-sm-12 container-fluid">
                                            <input type="text" class="form-control" id="mezuniyet_1">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <div class="m-0">
                                <p>Okul Fotoğrafı Yüklemek Butona Tıklayın Seçin</p>
                            </div>
                            <input type="file" class="form-control-file schoolfileinput" style="visibility:hidden" multiple="">
                             <input type="button" class="btn w-50 h-25 bg-dark text-white mb-4" value="seç" onclick="document.querySelector('.schoolfileinput').click();">
                        </div>
                        <div class="col-12">
                            <div class="row schoolarea">
                            </div>
                        </div>
                    </div>
                    <div id="customDiv_50" style="visibility:hidden">Custom Div 50</div>
                </div>
                <div class="col-1">
                    <button type="button" class="btn btn-success btn-sm mb-2" onclick="cloneForm(this)">+</button>
                    <button type="button" class="btn btn-danger btn-sm" onclick="clearForm('okulAlan_1')">-</button>
                </div>
            </div>

         

            <div class="d-flex justify-content-end">
                <input class="btn btn-primary" type="submit" value="Kaydet" id="Kaydet" onclick="Kaydet()">
            </div>
        </div>

     
        <div class="col-md-3 col-sm-12 mt-2 py-5 h-50 shadow-lg mb-5 bg-white rounded">
            <form id="fotoid">
                <div class="col-sm-12">
                    <div id="previewArea" class="row mb-4">
                        <img id="previewImage" src="#" alt="Fotoğraf Önizleme" style="display:none;" />
                        <div id="defaultText">
                            <p>Fotoğraf Yüklemek İçin Dosya Seçin</p>
                        </div>
                    </div>
                    <input type="file" class="form-control-file" id="photoUpload" style="visibility:hidden" multiple />
                    <input type="button" for="photoUpload" id="photojs" class="btn w-25 h-25 bg-dark text-white" value="seç" onclick="document.getElementById('photoUpload').click();" />
                </div>
            </form>

        </div>
   
    </div>
  
</div>
<script src="~/js/personelekleme.js"></script>
<script src="~/js/fotografonizleme.js"></script>
<script src="~/js/dropdown.js"></script>
<script src="~/js/tekrarlialan.js"></script>

OrsaAkademi.demo.WebApp/Views/PersonelEkleme/PersonelListesi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link href="~/css/medyaboyutlandirma.css" rel="stylesheet" />
<div class="container mt-5">
    <table id="dataTable" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Ad</th>
                <th>Soyad</th>
                <th>Telefon</th>
                <th>Email</th>
                <th>Doğum Tarihi</th>
                <th>Personel Fotoğrafı</th> 
                <th>Okul Adı</th> 
                <th>Mezun Yılı</th> 
                <th>Okul Fotoğrafı</th> 
                <th></th>
            </tr>
        </thead>




    </table>
</div>
<div class="container">
    <div class="col-12 d-flex justify-content-end">
        <button class="btn btn-success"><a class="nav-link text-white" asp-area="" asp-controller="PersonelEkleme" asp-action="PersonelEkleme">Personel Ekle</a> </button>
    </div>
</div>
<script src="~/js/personellisteleme.js"></script>